language: csharp
install:
    - nuget restore -PackagesDirectory packages
script:
    - xbuild /p:Configuration=Release Maxel/Maxel.csproj
before_deploy:
    - ./dist.sh
deploy:
    provider: releases
    api_key: RirIq1tTmPcd1xb6R+rSEZTr9Whgg+SUwvHp0TqBJLPuTZkMcmxtyCJb1NQ63gJXZk+WBNjDjQXdNgUb3T54xBocpq5ZT5uMoDk1miQ6NdWPeVriNTZgFoUO4M5Dx5L+pmEWscLBtBmHu8KZ+XEecB5vxwL2VEsGuA4CpibnZhZ1IkJpmFy1cADRHHq6wfLQlxYJsJR52HEuf/0gYSjzmuNE6m/5IcUcodYQT6+UBEWn0WSUDfmmZjKeDItdNS7Wx60YTUfRDzz25FBKH0JaxQf9QvLr9vbw/z10pVTrQmkQ+xef/E79RrdSZomWbqS7n+12Vs3DNUAy58Pg/TkRGxci9wsWfXfXIEHInNtuLBYUc+g9nCApUGouJ2CHj1CVXB9ssePjEUISXYdL8LU6TCECW2lOXLVNNBxKP9ihF2DKrzzkGFeuVgH3AdcNy6Dco8xHWNUSbLVCOtCzKP7hwFdfNsyL/it0wbjT86Lwo6eEcGkdZ1qv25j8yKY8TpBfya0C87nOw27GYkurlMtaKG1Yj4Z02pVA+X2QkSt9OKYzNPo9mhBWYM4iTyudQ4BiqZAISSKtsmFX836oBAxF4OnfGmoANu2NefOmUn/OmhMC2QOs5WC7zn4GcR7LLqlSs8xQGzKG5u/TgVxZnVpDpIxCNlNBYkf2vLJN3a10U00=
    file: Maxel/bin/Maxel-*.zip
    file_glob: true
    skip_cleanup: true
    on:
        tags: true
